### ISSUE TITLE
Uninstall? 

### ISSUE THREAD

**Issue by zfrenchee** [erasche/gxargparse#28]
Would you add an uninstall script? I assume just deleting the folder wouldn't be enough?

**Comment by erasche** [comment]
Hi @zfrenchee, how did you install gxargparse? 

If you installed it with `python setup.py install`, it should be as simple as `pip uninstall gxargparse`

**Comment by zfrenchee** [comment]
Didn't work for me, pip didn't think I had it installed. I just removed the directory.
