### ISSUE TITLE
Is gxargparse installed or not? 

### ISSUE THREAD

**Issue by zfrenchee** [erasche/gxargparse#29]
I make a virtualenv, clone the repo, run `python setup.py install` and it seems to terminate successfully, but when I try the test script, it fails, and I'm not quite sure why. 
```
Finished processing dependencies for gxargparse==0.2.5
(venv) computer:gxargparse Alex$ gxargparse_check_path
gxargparse not installed
```
Any ideas?

**Comment by erasche** [comment]
Try:

```
python setup.py develop
```

it's a bit finicky about installation method (and really shouldn't be installed anywhere outside of local venvs).

That said, it should `pip install gxargparse` properly, i.e. from pypi.

**Comment by zfrenchee** [comment]
works.
