### ISSUE TITLE
Is force_history_refresh="false" really the correct default?

### ISSUE THREAD

**Issue by erasche** [erasche/gxargparse#7]

**Comment by jmchilton** [comment]
That tag no longer does anything and there are no plans to revive it - I would just remove it all together.

**Comment by erasche** [comment]
Ah, thanks. Sorry for all the email spam with new issues!

**Comment by erasche** [comment]
[Removed from the wiki](https://wiki.galaxyproject.org/Admin/Tools/ToolConfigSyntax?action=diff&rev1=104&rev2=105)

**Comment by jmchilton** [comment]
Galaxy has a wiki?

**Comment by erasche** [comment]
And what a mistake it has been basing my DTDs/XSDs/XML generators off the only published docs...
